### ISSUE TITLE
the item values don't appear

### ISSUE THREAD

**Issue by mluis** [souly1/ion-select-picker#1]
Hello, I'm having a strange behaviour of the items not appearing in the picker.
Below is the code I'm using... Am I missing something?

Thanks.

HTML code:

`<input style="text-align: right; background-color: inherit;" type="text" ng-model="lsData.entityEmployees.selectedUser" ng-value="Name" items="lsData.entityEmployees.employees"  ng-readonly="true" ng-change="changedToAddNew()" ion-select-picker>`

Model Object: {{ lsData.entityEmployees.selectedUser }}

`{"Name": "Foo"}`

Items Object: {{ lsData.entityEmployees.employees }}

`[{"Name": "Foo"},{"Name": "Bar"}]`

**Comment by souly1** [comment]
Was this item solved as well?

**Comment by mluis** [comment]
It seems so. I've passed this step already. I'm closing the issue.

Thanks.
