### ISSUE TITLE
Select picker sending entire object not just string value.

### ISSUE THREAD

**Issue by Fyson** [souly1/ion-select-picker#3]
Hi there just got your select picker and it looks awesome and wasnt to hard to implement.

I do have a problem.

Im using your select picker so that the user can select a string value as part of a form and send the selected value. Everything works as expected but instead of just posting the stringvalue the select picker sends the entire object.

This is on my html page.
`<input type="text" placeholder="placeholder" ngDefault="placeholder" ng-model="form.owner" items="items.owners" ng-value="Name" class="addform" ng-readonly="true" isClickSelect="true" ion-select-picker>`

So i just wanna send the owners name. but this sends everything connected to that particular owner (Name, Avatar, etc, etc, etc,).

Update: Just noticed the DB saves this as "Array" cause of obvious reasons.

What am i doing wrong?

**Comment by Fyson** [comment]
1 week later and i stil havent found a way to fix this problem.
Is this supported in the selectbox?

**Comment by souly1** [comment]
Hi Fyson, I replied this but for some reason it did not get posted, must have forgotten to press the green button, sorry.
OK, so basically the select picker works in one of two modes:
1. objects - you pass array of objects and in items and the model holds the selected object. In such case if you'd want to send the name only in a form, assuming your using angular forms and not plain HTML, you'd need to catch the point prior to the form being sent and the extract the string value then. If you'd be using HTML forms then I'd set the name attribute of the input field to something and on model change set the correct string value to the input form field.
2. strings - in such case the control expects an array of strings and the model will eventually hold the selected string value. So in your case prior to loading the control (during the initialization of the page/form?) create an array of the owners names from the array of the owners and set the items attribute to it.

Update me on how it goes.
Thanks

**Comment by souly1** [comment]
Hey @Fyson , any update?

**Comment by souly1** [comment]
Closed due to lack of responsiveness, if you'll come back again we'll work on it, if still relevant.
Thanks
