### ISSUE TITLE
ion-select-picker (1.2.2) difficult to tap

### ISSUE THREAD

**Issue by mluis** [souly1/ion-select-picker#4]
Hello,

I had to change from angular on-click to angular on-tap in order to bypass certain iOS touch issues that change from version to version. (double touch in certain versions) 
It happens that now ion-select-picker is really difficult to open. Below is my code:

`<input style="text-align: right; background-color: inherit;" type="text" ng-model="lsData.alarmSettings.selected" items="lsData.alarmSettings.operations" ng-value="name" ng-readonly="true" ion-select-picker>`

Is it possible to enable the 'tap' event on it?

Thank you.
Best Regards,
Miguel

**Comment by souly1** [comment]
Hi Miguel,
I've had experience with this in the past with another directive, I'll look into it.

Thanks

**Comment by dochecknow** [comment]
Hey, I had the same issues on ios10 and i ended up tweaking the code slightly in the ionselectpicker.min.js file by changing the ng-click to on-tap for the set and cancel buttons, while also changing the one event listener from on.("click  to on.("tap

**Comment by souly1** [comment]
Hi @hughesy44 , thanks for the input, I'll try to get to this until the end of the week.

Thanks

**Comment by souly1** [comment]
Hi @mluis , please contact me via your purchase email, I think I might have a solution for your issue, thanks

**Comment by souly1** [comment]
Hey @mluis , are you going to contact me so we can examine the solution?

Thanks

**Comment by mluis** [comment]
Hey @souly1 , sorry for taking so long. Can I contact you Wednesday next week? I'm out of the office until then..

Thank You.

**Comment by souly1** [comment]
Sure, contact me when you got the time.\

thanks

**Comment by souly1** [comment]
Hi @mluis , @hughesy44  , thanks for bringing the issue to my attention, it has been fixed and new version released, make sure to download it.

Thanks

**Comment by mluis** [comment]
Hello @souly1 , sorry for this long delay. I just get back to the mobile app. I've changed them to the new version of both pickers (select and time) and can't get them to work. Although I've created a version in which I changed from the 'click' event to the 'tap' event and it worked with the version I opened this issue. I'm emulating the touch events in chrome. 

Thanks

**Comment by souly1** [comment]
Hi @mluis , make sure you've got the newest version as there were two, v2.1.1.
I've received info that 2.0.1 worked for iOS & iOS 10 (the problematic version) but caused issues in android, and on v2.1.1 returned to work in Android and iOS not clear yet (works for me on emulator)
Could you perhaps verify your version and check it, and if issue persists notify me and send me your purchase email, I'll send you a new version I believe will work (pretty much the solution that you've mentioned, just adding code to identify on iOS, since on Android the same code caused issues)

**Comment by mluis** [comment]
@souly1 I tried version 2.1.1, 30 minutes ago without success under the premisses of chrome touch events. I can send you my altered version if you want to check what can be wrong with v2.1.1 one.
The purchase was made by other person in which is not online right now. As soon I can talk with him, we will be in touch through the purchase email.

**Comment by souly1** [comment]
Thanks @mluis , no need, I'm checking with someone else, thanks.
Keep you updated

**Comment by souly1** [comment]
Issue solved in new version, Thanks.
