### ISSUE TITLE
Width of picker

### ISSUE THREAD

**Issue by LeonGreeff** [souly1/ion-select-picker#6]
Hi there, I wanted to know if I can set the width of the picker? I've modified the sizing in css, but then the picker's alignment of selection is completely wrong. By default it seems, longer text with a space or so between makes the text wrap and alignment becomes is an issue. Any tips to fix this, thanks a lot!

**Comment by souly1** [comment]
Hi @LeonGreeff , thanks for reaching out.
It should be possible to change the width as I know several clients have already done so.
Please try to load the component in the browser and open the developer console to debug and identify exactly all the elements in the DOM tree which require change of width.

Let me know how it works out

**Comment by LeonGreeff** [comment]
Thanks  a lot @souly1 , I'm still missing something though. My apologies if it is a simple thing I'm missing here. I've playing with the css to achieve me desired output, I added this:

```
.isp-item-c
{
    
    width:300px;
}

.isp-item-cs
{
    
    width:300px;
}

.isp-drawer .ios-c
{
    width:300px;
    
}

.isp-drawer .ios-container
{
    width:300px;
    
}
.isp-item-n
{
    width:300px !important;    
    overflow: hidden;
}
```

It looks perfect, and works with the first few items, but as I scroll further, about 5 to 10 items down..it becomes out of sync completely...appreciate  your feedback! thanks!

**Comment by souly1** [comment]
Hi Leon, are you sure all the data is exactly one line? it is possible the control went out of sync due to multiline data.
If so, could you perhaps check it with simple short length strings as data to see if issue persists?
Thanks

**Comment by LeonGreeff** [comment]
Yes one line, the input does not support multi line..so weird..wonder if it could be certain characters or something...I have a clip to show the result.

https://drive.google.com/open?id=0B-baugSIJGTmUTRYZXdmcS1WdlE

**Comment by souly1** [comment]
@LeonGreeff , I see you have very long lines here, did you examine that indeed each value is displayed only on a single line and did not wrap onto another? could you perhaps try to change values to shorter lengths such as the 'mom' value you set just to see if things change.
Also, Just making sure, you did not change anything about the height, right?

**Comment by souly1** [comment]
Hey @LeonGreeff , any update?

**Comment by LeonGreeff** [comment]
Not quite. It works when I remove some characters at the end, with something like substring. Is it possible to get the unminified code? I want to change it slightly where It displays a shorter string with '...' but after selection, selects the entire word. With css text-overflow etc. it still does not work properly, only works when the actual array of items have shorter names. Thanks!

**Comment by souly1** [comment]
Sorry, but sharing the code is not possible.
to do what you want you can use ngValue, so instead of using basic strings you use objects, and in the ng-value place the short version of the string.
Example:
`<input class="input-field" placeholder="Select Country..." required readonly="" type="text"  items='selectItems' ng-value="shortName" ng-model="myTextPicker" control="selectControl" ion-select-picker/>
`

and in`selectControl` above:
`//possible items:
$scope.selectItems = [{
  id:0,
  name: 'this is a very long name',
  shortName: 'this is a v...'
},{
 id:1,
 name: 'another element',
 shortName: 'another element'
}]
`

Through trial and error you'll be able to know the exact number of characters you can display and truncate the name with 3 dots accordingly.
Take note that what later is set to the ng-model (`myTextPicker` above) is the actual object and not just the string value.

Tell me if this helps with the issue.

Thanks

**Comment by souly1** [comment]
Any update @LeonGreeff ?

**Comment by LeonGreeff** [comment]
Hi @souly1 , 

Have no solution yet, very strange. Is it possible to pass in two different values? One to display in the picker (a shorter version, not with css and overflow hidden, actual shorter version) and after selection, show the longer version in the textbox? I found that having shorter text, it works fine. I checked the data, no funny characters etc.

Thanks!

**Comment by souly1** [comment]
Hi @LeonGreeff , what you are specifying is exactly what i wrote above using ngValue.
Try it out and update how it goes.

**Comment by LeonGreeff** [comment]
Thanks @souly1, I apologise, I somehow totally missed that post, just read the "any update" post ;-)  Will do it asap and let you know!

**Comment by LeonGreeff** [comment]
Actually, this is what I have, but after selection, (in your example) the display will also be "shortName", thus the text box shows 'this is a v...'

![image](https://cloud.githubusercontent.com/assets/7512057/23645894/21cee4be-0317-11e7-95a2-ffd450b1f3d1.png)

**Comment by LeonGreeff** [comment]
I need like a ng-value and "ng-display-value".

**Comment by LeonGreeff** [comment]
..maybe I can decorate / extend the directive...but I guess that will be some work. Need to get this build out. Any ideas to get this sort of functionality? Thanks for your time.

**Comment by souly1** [comment]
Hi @LeonGreeff .
Added attribute `ng-model-display-value` (optional) - Define how to display the value in ngModel, in case it differs from actual model or ngValue. Update if issue closed.

**Comment by souly1** [comment]
BTW, I'm presuming your using <input> element and that's why the ngModel value is displayed. another option would be to use a basic <div> and set into it any text you'd like

**Comment by LeonGreeff** [comment]
AWESOME!! Thank you so much, you rock.
